---
- hosts: all
  tasks:
    - name: yarn
      command: "yarn"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: yarn test
      command: "yarn test"
      args:
        chdir: "{{ zuul.project.src_dir }}"
